### ISSUE TITLE
我想抛下看看效果但是似乎缺少这个文件-OrigamiSolver

### ISSUE THREAD

**Issue by HanHailiang** [zzhuyii/GenerateOrigamiDataSet#1]
![image](https://user-images.githubusercontent.com/26705398/176884145-4d0b4609-a309-47c4-8e9f-e29c88feea81.png)

**Comment by zzhuyii** [comment]
Hello,
你需要下载SWOMPS的package，分析的源代码在那个包里面。我的Github里面有一个叫"OrigamiSimulator"的repo。
