### ISSUE TITLE
我仔细阅读了您撰写的论文Harnessing Interpretable Machine Learning for Origami Feature Design and Pattern Selection

### ISSUE THREAD

**Issue by HanHailiang** [zzhuyii/GenerateOrigamiDataSet#2]
但是在论文中提到有补充材料S3.3，不过我没有找到这个材料，方便提供下么
![image](https://user-images.githubusercontent.com/26705398/177284931-eacada2e-3f9c-49f6-bce1-19bc30949f83.png)

**Comment by zzhuyii** [comment]
Hello,
这个部分就是附的这几张图。第一张图是ML算法检验的过程。我们使用的是最基础的hold out testing。
后面几张图则是grid search的主要结果。理想情况我们是需要对每一个目标每一个database都单独进行一次grid
search。不过论文中最后就用了一组综合看起来比较好的参数。
希望对你有帮助。

[image: Crossvalidation.png]
[image: GridSearch_Arch.png][image: GridSearch_Canopy.png][image:
GridSearch_Gripper.png]

**Comment by zzhuyii** [comment]
Hmm, not sure if Git is able to show the figures. If you are not able to get the image showing. Please send me an email at: yizhucee@umich.edu
